fix

diff --git a/bash/scripts/bin/mac-scan b/bash/scripts/bin/mac-scan
--- a/bash/scripts/bin/mac-scan
+++ b/bash/scripts/bin/mac-scan
@@ -1,14 +1,35 @@
 #!/bin/bash
 
+USAGE="Usage: $(basename "$0") [-r] [-i ethx] MAC_ADDR -- set the mac address
+
+Options:
+    -i          sets the network interface (defaults to wlan0)
+"
+
 IFACE=wlan0
+
+while getopts 'i:' OPT; do
+    case "$OPT" in
+        h)
+            echo "$USAGE"
+            exit
+            ;;
+        i)
+            IFACE=$OPTARG
+            ;;
+        *)
+            echo 'Invalid option: '$OPT
+            echo $USAGE
+            exit 1
+    esac
+done
+shift $((OPTIND - 1))
 
 GATEWAY=`netstat -nr | grep '^0.0.0.0' | awk '{print $2}'`
 MASK=${GATEWAY%.*}".0"
 # scan all IPs where the first NUMBITS are the same
 NUMBITS=24
 
-echo "mask: "$MASK
-
-echo "scanning "$MASK
+# echo "scanning "$MASK
 # sudo nmap -sn -oG - $MASK"/"$NUMBITS
 sudo nmap -sn $MASK"/"$NUMBITS | awk '/Nmap scan report/{if (!$6) {printf "(unknown) (";printf $5;printf ")"} else {printf $5;printf " ";printf $6};getline;getline;printf " ";if ($1 == "MAC") { print $3 } else { print "(missing)" }}' | column -t
